### PR TITLE
Add get restrictions ? 

### PR DESCRIPTION
**Pull request by projectoblio**
This will allow you to restrict based on get too to reduce bandwidth costs

### CODE REVIEW

**Comment by zrrrzzt** [comment]
Thank you for your additions to this module :-)

Can you please update the README.md as well to match the changes?

**Comment by projectoblio** [comment]
Sure thanks. I have added that.

**Comment by projectoblio** [comment]
i hate git and github. one second

**Comment by projectoblio** [comment]
I don't know how to do that anymore.

**Pull request closed without merging**
